# Generated by Django 5.2.1 on 2025-05-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("location", models.IntegerField()),
                ("date_of_birth", models.DateField()),
                ("iban", models.TextField()),
                ("bic", models.TextField()),
            ],
        ),
    ]
