# Generated by Django 5.2.1 on 2025-05-16 17:25
#
# See https://docs.djangoproject.com/en/5.2/topics/migrations/#data-migrations for documentation on data migrations
#

from django.db import migrations


def create_example_staff_members(apps, schema_editor):
    # We can't import the model directly as it may be a newer version than this
    # migration expects. We use the historical version.
    Staff = apps.get_model("weird_salads_staff", "Staff")
    for details in [
        {
            "name": "Velva Shields",
            "location": 1,
            "date_of_birth": "1976-07-30",
            "iban": "GB49VHZF63392981589063",
            "bic": "AAPUGB21",
        },
        {
            "name": "Francesco Schinner",
            "location": 18,
            "date_of_birth": "1997-07-01",
            "iban": "GB90IBXP65333147911131",
            "bic": "ABECGB21",
        },
    ]:
        staff = Staff(
            name=details["name"],
            location=details["location"],
            date_of_birth=details["date_of_birth"],
            iban=details["iban"],
            bic=details["bic"],
        )
        staff.save()


class Migration(migrations.Migration):
    dependencies = [
        ("weird_salads_staff", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_example_staff_members),
    ]
