"""Add sample staff data

Revision ID: ea5005765bc6
Revises: 50fc5d40310d
Create Date: 2025-05-16 15:26:47.486113

"""

from typing import Sequence, Union

from alembic import op
from weird_salads.models import Staff

# revision identifiers, used by Alembic.
revision: str = "ea5005765bc6"
down_revision: Union[str, None] = "50fc5d40310d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.bulk_insert(
        Staff.__table__,
        [
            {
                "staff_id": 3,
                "name": "Velva Shields",
                "date_of_birth": "1976-07-30",
                "iban": "GB49VHZF63392981589063",
                "bic": "AAPUGB21",
                "location": 1,
            }
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
